feat: clin_sig spell
datavzrd/datavzrd-spells pull request #13
Opened 2024-11-16 09:14 UTC by BenOrl

New spell to visualize the clinical significance

2024-11-16 09:52 UTC, fxwiegand commented
Just as a general info: There is no need to open up a new PR if there is a new change. Simply push another commit to the branch of the currently opened PR and the one already open will update.

2024-11-19 12:42 UTC, johanneskoester requested changes

2024-11-19 12:42 UTC, johanneskoester commented on sign/clin_sig/meta.yaml
> +type: "column consistent of strings, separated by ',' "
```suggestion
type: "column consisting of strings, separated by ',' "
```

2024-11-19 12:42 UTC, johanneskoester commented on sign/clin_sig/meta.yaml
> +link-to-url: https://www.ncbi.nlm.nih.gov/clinvar/
Is this used in the docs? Maybe rather annotate the mention of clinvar in the description above with a markdown link.

2024-11-19 12:42 UTC, johanneskoester commented on sign/clin_sig/meta.yaml
> +        Significance Column:
The column name is not optimal. Maybe rather "clinical significance"?

2024-11-22 11:37 UTC, FelixMoelder commented
To get the tests passing some changes are required. Here is a summary as I do not have write access and github suggestions would get a bit out of hand.

- `test_*.yaml` and `data*.tsv` must be placed in a subdirectory called `tests`
- `test*.yaml`:
  -  files need an underscore e.g `test_*.yaml`
  - `url` and `path` need to be relative to the yaml-file's location 
  - the column name should match the one set in the `data*.tsv`
- `data*.tsv`: choose a more generic column name as this is just an example e.g. `some clinical significance column` (optional) 
- `meta.yaml`:
  - `type` needs to be `column` as it is not a description field
  - check for correct indentation and spelling of `test-data` 
  - adjust the path after moving the yaml-file into a subdirectory 
- `spell.yaml`: the function must not have a name to be called

2024-11-26 09:43 UTC, fxwiegand commented on sign/clin_sig/tests/test_1.yaml
> +            url: sign/clin_sig/spell.yaml
```suggestion
            url: ../spell.yaml
```

2024-11-26 09:44 UTC, fxwiegand commented on sign/clin_sig/tests/test_2.yaml
> +            url: sign/clin_sig/spell.yaml
```suggestion
            url: ../spell.yaml
```

2024-11-26 09:44 UTC, fxwiegand commented on sign/clin_sig/tests/test_3.yaml
> +            url: sign/clin_sig/spell.yaml
```suggestion
            url: ../spell.yaml
```

2024-11-26 13:54 UTC, fxwiegand commented on sign/clin_sig/tests/test_1.yaml
> +      path: sign/clin_sig/tests/data1.tsv
```suggestion
      path: data1.tsv
```

2024-11-26 13:54 UTC, fxwiegand commented on sign/clin_sig/tests/test_2.yaml
> +      path: sign/clin_sig/tests/data2.tsv
```suggestion
      path: data2.tsv
```

2024-11-26 13:55 UTC, fxwiegand commented on sign/clin_sig/tests/test_3.yaml
> +      path: sign/clin_sig/tests/data3.tsv
```suggestion
      path: data3.tsv
```

2024-11-26 13:56 UTC, fxwiegand requested changes
The paths to the files containing the test data also need be be relative - sorry I should've noticed that in the last review 😅

2024-11-26 15:07 UTC, FelixMoelder commented on sign/clin_sig/meta.yaml
> +  test-data: sign/clin_sig/tests/data1.tsv
```suggestion
  test-data: tests/data1.tsv
```

2024-11-26 15:09 UTC, FelixMoelder commented
To me this looks good now.

2024-11-26 15:11 UTC, FelixMoelder commented on default.profraw
This should also be removed

2024-11-26 15:15 UTC, FelixMoelder commented
@johanneskoester should the directory more contextual like `bio/clin_sig` or `annotation/clin_sig`?

2024-11-26 15:27 UTC, johanneskoester commented
> @johanneskoester should the directory more contextual like `bio/clin_sig`, ~`vep/clin_sig`~ or `annotation/clin_sig`?

`bio/clin-sig` I would say.

2024-11-27 06:57 UTC, FelixMoelder approved these changes

2024-11-27 06:58 UTC, FelixMoelder commented
Looks got to me.

2024-11-27 09:06 UTC, fxwiegand approved these changes

2024-11-27 09:17 UTC, merged